name: Farhan Ali

on:
  schedule:
    - cron: "15 20 * * *"
  workflow_dispatch:

jobs:
  scheduling-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Schedule
        run: echo "Scheduled Github Actions Workflow"
